package com.evidencepilot.client.ai.gate;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

@JdbcTest
@Import(AiModelCallPolicy.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class AiModelCallPolicyTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private AiModelCallPolicy policy;

    @BeforeEach
    void resetGateTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ai_model_gate_state (
                    gate_key VARCHAR(32) PRIMARY KEY,
                    next_allowed_at TIMESTAMP(6) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ai_model_call_leases (
                    lease_id CHAR(36) PRIMARY KEY,
                    expires_at TIMESTAMP(6) NOT NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ai_model_call_outcomes (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    breaker_failure BOOLEAN NOT NULL,
                    occurred_at TIMESTAMP(6) NOT NULL
                )
                """);
        jdbcTemplate.update("DELETE FROM ai_model_call_outcomes");
        jdbcTemplate.update("DELETE FROM ai_model_call_leases");
        jdbcTemplate.update("DELETE FROM ai_model_gate_state");
        jdbcTemplate.update("""
                INSERT INTO ai_model_gate_state (gate_key, next_allowed_at)
                VALUES ('model', CURRENT_TIMESTAMP)
                """);
    }

    @Test
    void concurrentInstancesReserveGloballySpacedStarts() throws Exception {
        CountDownLatch ready = new CountDownLatch(2);
        CountDownLatch start = new CountDownLatch(1);
        try (var executor = Executors.newFixedThreadPool(2)) {
            var first = executor.submit(() -> reserveAfterSignal(ready, start));
            var second = executor.submit(() -> reserveAfterSignal(ready, start));
            assertThat(ready.await(2, TimeUnit.SECONDS)).isTrue();
            start.countDown();

            List<Long> waits = List.of(
                    first.get(5, TimeUnit.SECONDS),
                    second.get(5, TimeUnit.SECONDS));
            assertThat(waits.stream().mapToLong(Long::longValue).max().orElseThrow()
                    - waits.stream().mapToLong(Long::longValue).min().orElseThrow())
                    .isGreaterThanOrEqualTo(900);
        }
    }

    @Test
    void concurrentInstancesShareTheConcurrencyLimit() throws Exception {
        CountDownLatch ready = new CountDownLatch(2);
        CountDownLatch start = new CountDownLatch(1);
        try (var executor = Executors.newFixedThreadPool(2)) {
            var first = executor.submit(() -> leaseAfterSignal(ready, start));
            var second = executor.submit(() -> leaseAfterSignal(ready, start));
            assertThat(ready.await(2, TimeUnit.SECONDS)).isTrue();
            start.countDown();

            List<String> leases = Arrays.asList(
                    first.get(5, TimeUnit.SECONDS),
                    second.get(5, TimeUnit.SECONDS));
            assertThat(leases).containsNull();
            assertThat(leases).filteredOn(lease -> lease != null).hasSize(1);
        }
    }

    @Test
    void circuitOpensOnlyAboveHalfOfAtLeastTwentyFinalCalls() {
        for (int index = 0; index < 20; index++) {
            policy.recordFinalOutcome(index < 10);
        }
        assertThat(policy.isCircuitOpen()).isFalse();

        policy.recordFinalOutcome(true);
        assertThat(policy.isCircuitOpen()).isTrue();
    }

    private long reserveAfterSignal(CountDownLatch ready, CountDownLatch start)
            throws InterruptedException {
        ready.countDown();
        assertThat(start.await(2, TimeUnit.SECONDS)).isTrue();
        return policy.reserveStart(1_000);
    }

    private String leaseAfterSignal(CountDownLatch ready, CountDownLatch start)
            throws InterruptedException {
        ready.countDown();
        assertThat(start.await(2, TimeUnit.SECONDS)).isTrue();
        return policy.tryAcquireLease(1, 60_000);
    }
}
